apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ordertracker.name" . }}
type: Opaque
data:
  consumerKey: {{ .Values.backend.consumerKey }}
  consumerSecret: {{ .Values.backend.consumerSecret }}
  accessToken: {{ .Values.backend.accessToken }}
  accessTokenSecret: {{ .Values.backend.accessTokenSecret }}
  authToken: {{ .Values.backend.authToken }}
